//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vyfvyf
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прикол.
    /// </summary>
    // *** Start programmer edit section *** (Прикол CustomAttributes)

    // *** End programmer edit section *** (Прикол CustomAttributes)
    public enum Прикол
    {
        
        /// <summary>
        /// 1.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.Ладно CustomAttributes)

        // *** End programmer edit section *** (Прикол.Ладно CustomAttributes)
        [Caption("5")]
        Ладно = 3,
        
        /// <summary>
        /// 2.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.пока CustomAttributes)

        // *** End programmer edit section *** (Прикол.пока CustomAttributes)
        [Caption("6")]
        пока = 4,
        
        /// <summary>
        /// 7.
        /// </summary>
        // *** Start programmer edit section *** (Прикол.пвапва CustomAttributes)

        // *** End programmer edit section *** (Прикол.пвапва CustomAttributes)
        [Caption("9")]
        пвапва = 8,
    }
}
